insert into insurance_product values ('P1', 'PRODUCT1');
insert into coverage_item values ('C1', 'COVER1', 'P1');
insert into coverage_item_option values ('CO00', '0', 'C1');
insert into coverage_item_option values ('CO01', '500', 'C1');
insert into coverage_item_option values ('CO02', '750', 'C1');
insert into coverage_item_option values ('CO03', '1000', 'C1');
insert into coverage_item values ('C2', 'COVER2', 'P1');
insert into coverage_item_option values ('CO04', '0', 'C2');
insert into coverage_item_option values ('CO05', '250', 'C2');
insert into coverage_item_option values ('CO06', '300', 'C2');
insert into coverage_item_option values ('CO07', '350', 'C2');
insert into insurance_product values ('P2', 'PRODUCT2');
insert into coverage_item values ('C3', 'COVER3', 'P2');
insert into coverage_item_option values ('CO08', '0', 'C3');
insert into coverage_item_option values ('CO09', '500', 'C3');
insert into coverage_item_option values ('CO10', '750', 'C3');
insert into coverage_item_option values ('CO11', '1000', 'C3');
insert into coverage_item values ('C4', 'COVER4', 'P2');
insert into coverage_item_option values ('CO12', '0', 'C4');
insert into coverage_item_option values ('CO13', '250', 'C4');
insert into coverage_item_option values ('CO14', '300', 'C4');
insert into coverage_item_option values ('CO15', '350', 'C4');